name: Update nbox docs
on:
  push:
    branches: [master, docs]
    paths:
      - "docs-src/**"
  workflow_dispatch:
jobs:
  docs-gen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
      - name: Install Sphinx, furo, nbox-dependencies
        run: |
          sudo apt-get -y install python3-sphinx
          pip install furo
          pip install -r requirements.txt
      - name: Make html
        working-directory: "docs-src/"
        run: |
          make github
        env:
          NBX_AUTH: 1
          
      - name: Commit docs
        run: |
          git config --global user.name "NimbleBox Research"
          git config --global user.email 'research@nimblebox.ai'
          git add docs/
          git commit -m "Update Docs"
          git push
